on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - 'SnakePro_server.pck'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - run: |
        echo Deploying!
        kill $(pgrep -f SnakePro_server.) || true
        cd /home/docker/
        mkdir -p snakepro
        cd snakepro
        curl -L https://github.com/mar511n/SnakePro/raw/main/executables/SnakePro_server.x86_64 -o SnakePro_server.x86_64
        curl -L https://github.com/mar511n/SnakePro/raw/main/executables/SnakePro_server.pck -o SnakePro_server.pck
        chmod +x ./SnakePro_server.x86_64
        ./SnakePro_server.x86_64 > /dev/null 2>&1 &
        echo Finished deploying!
