on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - 'SnakePro_server.pck'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - run: |
        echo Deploying!
        top -bn1
        kill $(pgrep -f SnakePro_server.)
        mkdir -p snakepro
        cd skanepro
        curl https://github.com/mar511n/SnakePro/blob/main/executables/SnakePro_server.x86_64 -o SnakePro_server.x86_64
        curl https://github.com/mar511n/SnakePro/blob/main/executables/SnakePro_server.pck -o SnakePro_server.pck
        ./SnakePro_server.x86_64 </dev/null &>/dev/null &
        
